APPLICATION = read_dht_values

BOARD ?= esp32-wroom-32

RIOTBASE ?= $(HOME)/RIOT

DEVELHELP ?= 1

QUIET ?= 1

FEATURES_OPTIONAL += periph_timer

USEMODULE += periph_gpio
USEMODULE += dht

include $(RIOTBASE)/Makefile.include
